/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Negocios.Conector;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Jonnathan Campoberde
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    static ArrayList<String> datosTabla = new ArrayList<>();
    static TableModel modeloTabla;

    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Menú");
        setIconImage(new ImageIcon(getClass().getResource("../Img/usuarioProyectoImagen.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTblProducto = new javax.swing.JTable();
        jbtnRealizarPedido = new javax.swing.JButton();
        jLblTipoServicio = new javax.swing.JLabel();
        jLblNumServicio = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(480, 635));
        getContentPane().setLayout(null);

        jTblProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTblProducto);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 250, 440, 270);

        jbtnRealizarPedido.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jbtnRealizarPedido.setText("Realizar Pedido");
        jbtnRealizarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRealizarPedidoActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnRealizarPedido);
        jbtnRealizarPedido.setBounds(300, 520, 150, 40);

        jLblTipoServicio.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jLblTipoServicio.setText("Servicio:");
        getContentPane().add(jLblTipoServicio);
        jLblTipoServicio.setBounds(20, 220, 90, 19);

        jLblNumServicio.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLblNumServicio.setText("# Mesa");
        getContentPane().add(jLblNumServicio);
        jLblNumServicio.setBounds(110, 220, 60, 19);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/EL RINCONCILOMenu.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 464, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnRealizarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRealizarPedidoActionPerformed

    }//GEN-LAST:event_jbtnRealizarPedidoActionPerformed

    public void setDatosServicio() {
        String[] datosServicio = SolicitarServicio.getDatosClienteServicio();
        jLblTipoServicio.setText(datosServicio[0] + ": ");
        jLblNumServicio.setText(datosServicio[1]);
        setProducto();
    }

    public void stop() {
        this.dispose();
    }

    public ArrayList<String> getPedido() {
        this.dispose();
        datosTabla.clear();
        String fila[];
        modeloTabla = jTblProducto.getModel();
        datosTabla.add(jLblTipoServicio.getText() + "," + jLblNumServicio.getText());
        for (int i = 0; i < modeloTabla.getRowCount(); i++) {
            if (((modeloTabla.getValueAt(i, 4)).toString()).compareTo("0") != 0) {
                datosTabla.add(modeloTabla.getValueAt(i, 0) + "," + modeloTabla.getValueAt(i, 4));
            }
        }
        /*for (int i = 0; i < datosTabla.size(); i++) {
            System.out.println(datosTabla.get(i) + " ");
        }*/
        JOptionPane.showMessageDialog(null, "El pedido esta siendo procesado, por favor espere.....", "Estado", JOptionPane.INFORMATION_MESSAGE);
        return datosTabla;
    }

    public void setProducto() {
        String[] datosServicio = SolicitarServicio.getDatosClienteServicio();
        ArrayList<String[]> datos = Conector.getProductos(datosServicio[0]);
        int numColumnas = datos.get(0).length + 1;
        String[] columnas = new String[numColumnas];
        for (int i = 0; i < numColumnas - 1; i++) {
            columnas[i] = datos.get(0)[i];
        }
        columnas[numColumnas - 1] = "Cantidad";
        Object[][] datosProductos = new Object[datos.size() - 1][numColumnas];
        for (int i = 1; i < datos.size(); i++) {
            for (int j = 0; j < datos.get(i).length; j++) {
                datosProductos[i - 1][j] = datos.get(i)[j];
            }
            datosProductos[i - 1][columnas.length - 1] = "0";
        }
        DefaultTableModel modeloTabla = new DefaultTableModel(datosProductos, columnas);
        jTblProducto.setModel(modeloTabla);
    }

    public void setDatosServio(String datos[]) {
        SolicitarServicio.getDatosClienteServicio();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLblNumServicio;
    public javax.swing.JLabel jLblTipoServicio;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTblProducto;
    public javax.swing.JButton jbtnRealizarPedido;
    // End of variables declaration//GEN-END:variables
}
