/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Negocios.Conector;
import java.awt.event.ItemEvent;
import javax.swing.ImageIcon;

/**
 *
 * @author Jonnathan Campoberde
 */
public class SolicitarServicio extends javax.swing.JFrame {

    /**
     * Creates new form SolicitarServicio
     */
    public SolicitarServicio() {
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("../Img/usuarioProyectoImagen.png")).getImage());
        cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jCbxServicioCliente = new javax.swing.JComboBox<>();
        jCmbDisponiblesUsuario = new javax.swing.JComboBox<>();
        jBtnSolicitarPedido = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(518, 295));
        setPreferredSize(new java.awt.Dimension(530, 274));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/VER PROD.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 70, 70, 70);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel1.setText("Servicio:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 80, 90, 22);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel4.setText("Disponibles:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(120, 130, 100, 22);

        jCbxServicioCliente.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jCbxServicioCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bar", "Restaurante" }));
        jCbxServicioCliente.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCbxServicioClienteItemStateChanged(evt);
            }
        });
        getContentPane().add(jCbxServicioCliente);
        jCbxServicioCliente.setBounds(230, 80, 250, 32);

        jCmbDisponiblesUsuario.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jCmbDisponiblesUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jCmbDisponiblesUsuario);
        jCmbDisponiblesUsuario.setBounds(230, 130, 250, 29);

        jBtnSolicitarPedido.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jBtnSolicitarPedido.setText("Pedir Servicio");
        jBtnSolicitarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSolicitarPedidoActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnSolicitarPedido);
        jBtnSolicitarPedido.setBounds(310, 200, 170, 31);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/fondoTipoServicio.png"))); // NOI18N
        jLabel3.setToolTipText("");
        jLabel3.setMaximumSize(new java.awt.Dimension(550, 274));
        jLabel3.setMinimumSize(new java.awt.Dimension(550, 274));
        jLabel3.setPreferredSize(new java.awt.Dimension(550, 274));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(1, -4, 520, 280);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCbxServicioClienteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCbxServicioClienteItemStateChanged
   
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            cargarDatos();
        }
    }//GEN-LAST:event_jCbxServicioClienteItemStateChanged

    private void jBtnSolicitarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSolicitarPedidoActionPerformed
        Conector.iniciarMenu();
        getDatosClienteServicio();
        this.dispose();
    }//GEN-LAST:event_jBtnSolicitarPedidoActionPerformed

    
    public static String[] getDatosClienteServicio(){
        String[] datos=new String[2];
        datos[0]=jCbxServicioCliente.getSelectedItem().toString();
        datos[1]=jCmbDisponiblesUsuario.getSelectedItem().toString();
        return datos;
    }
    
    public static String getServicio(){
        return jCbxServicioCliente.getSelectedItem().toString();
    }
    
    public void cargarDatos(){
        String datos[];
        datos=Conector.getDisponibles(jCbxServicioCliente.getSelectedItem().toString());
            jCmbDisponiblesUsuario.removeAllItems();
            for (int i = 0; i < datos.length; i++) {
               jCmbDisponiblesUsuario.addItem(datos[i]);
            }
    }
    
    public void stop(){
        this.dispose();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SolicitarServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SolicitarServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SolicitarServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SolicitarServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SolicitarServicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jBtnSolicitarPedido;
    public static javax.swing.JComboBox<String> jCbxServicioCliente;
    private static javax.swing.JComboBox<String> jCmbDisponiblesUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
